#cloud-config

# Aliases: apt_update, apt_upgrade
package_update: true
package_upgrade: true

packages:
  - git
  - python3-pip
  
runcmd:
  #Installation of docker
  - 'sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release'
  - 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg'
  - 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null'
  - 'sudo apt-get update'
  - 'sudo apt-get install -y docker-ce docker-ce-cli containerd.io'

  #Installation of pulsar
  - 'sudo wget https://archive.apache.org/dist/pulsar/pulsar-2.7.0/apache-pulsar-2.7.0-bin.tar.gz'
  - 'sudo tar xvfz apache-pulsar-2.7.0-bin.tar.gz'
  - 'rm -rf apache-pulsar-2.7.0-bin.tar.gz'
  - 'sudo mv apache-pulsar-2.7.0/ home/ubuntu/apache-pulsar-2.7.0'
  - 'sudo pip3 install pulsar-client==2.7.1'

  #Installation of java
  - 'sudo apt install openjdk-11-jre-headless -y'

  #Reboot after all the updates
  #- 'sudo reboot'