version: '3.1'

services:

  consumerq1:
    build:
      context: pulsar_src/
      dockerfile: consumerQ1.Dockerfile
    restart: always

  # consumerq2:
  #   build:
  #     context: pulsar_src/
  #     dockerfile: consumerQ2.Dockerfile
  #   restart: always

  consumerq3:
    build:
      context: pulsar_src/
      dockerfile: consumerQ3.Dockerfile
    restart: always

  # consumerq4:
  #   build:
  #     context: pulsar_src/
  #     dockerfile: pulsar_src/consumerQ4.Dockerfile
  #   restart: always

  producer:
    build:
      context: pulsar_src/
      dockerfile: producer.Dockerfile