version: '3.1'

services:

  consumerq1:
    build: pulsar_src/
    restart: always
    entrypoint: ["python3", "consumerQ1.py"]

  consumerq2:
    build: pulsar_src/
    restart: always
    entrypoint: ["python3", "consumerQ2.py"]

  consumerq3:
    build: pulsar_src/
    restart: always
    entrypoint: ["python3", "consumerQ3.py"]

  consumerq4:
    build: pulsar_src/
    restart: always
    entrypoint: ["python3", "consumerQ4.py"]

  producer:
    build: pulsar_src/
    entrypoint: ["python3", "producer_continuous.py"]